### ISSUE TITLE
Tensorflow.js部署问题

### ISSUE THREAD

**Issue by iotsharer** [AIZOOTech/FaceMaskDetection#1]

**Comment by iotsharer** [comment]
请问Tensorflow.js部署代码开源吗？公众号已经关注，希望公众号后期可以推出模型部署的教程

**Comment by AIZOOTech** [comment]
TensorFlow.js是一个非常简单的东西，推荐一个库 ml5js。一个基于TensorFlow.js的机器学习库。有需要获取源码的可以添加微信号小助手AIZOOTech联系。
