### ISSUE TITLE
关于数据集中的非法标签

### ISSUE THREAD

**Issue by zhiyiYo** [AIZOOTech/FaceMaskDetection#109]
发现数据集中有的标签没有边界框，有的标签没有图像大小信息，有的图像大小信息为 0，所以我清理了一下数据集并重新组织了数据集为 Pascal VOC2007 的目录结构，数据集放在了 Kaggle 上，链接为： https://www.kaggle.com/datasets/zhiyiyo/face-mask-dataset

**Comment by lyx323** [comment]
已收到

**Comment by AydenLii** [comment]
@zhiyiYo 非常感谢你的贡献，我正在尝试你的工作，现已经下载使用。感谢你的帮助。
