### ISSUE TITLE
One of the images in your dataset 'test_00000306.xml' has a false category

### ISSUE THREAD

**Issue by SkeletonOne** [AIZOOTech/FaceMaskDetection#15]
Thanks for your excellent work! I am using the dataset you provide to train a detection network. While turning the annotations into .json format, I found out that the image 'test_00000306.xml' in the val set has a category named 'face_nask'. I'm sure it's a typo, hope you can correct it. :)

**Comment by AIZOOTech** [comment]
I really appreciate it.

**Comment by SkeletonOne** [comment]
@AIZOOTech Okay, I've trained your dataset on retinanet for 2 epochs with a batch size of 2. However, the result seems awful. I was hoping that the performance should be better for this task. So how many epochs have you trained on SSD?

**Comment by AIZOOTech** [comment]
Batch size == 2 ? Why do you set it so small ? The RetinaNet is very big ? I trained the ssd net for about 50 epoches.

**Comment by Ndron** [comment]
@SkeletonOne @AIZOOTech 
Can you share link to train dataset please?
my mail: shrabster12@gmail.com
