### ISSUE TITLE
请问在keras或者tf2.0上如何将conv和bn进行融合？

### ISSUE THREAD

**Issue by TCBocean** [AIZOOTech/FaceMaskDetection#34]
请问在keras或者tf2.0上如何将conv和bn进行融合？
是否有代码教程？可以分享一下吗？
非常感谢~

**Comment by AIZOOTech** [comment]
我在这篇公众号文章中介绍了如何融合 [深度学习推理时融合BN，轻松获得5%的加速](https://mp.weixin.qq.com/s/PXsyy-WBqxA5FTMFseC9Rw)
欢迎关注我们的公众号 AIZOO， 获得最及时的更新。
