### ISSUE TITLE
i open face_mask_detection.tflite via Netron, why the dimension of this are [1, 5972, 4] and [1,5972, 2] ?

### ISSUE THREAD

**Issue by VHCC** [AIZOOTech/FaceMaskDetection#40]
I want to use face_mask_detection.tflite port into android. 
and there is a question, why label just 2 type [NoMask, Mask], but the dimension of this file are [1, 5972, 4] and [1,5972, 2] ?

**Comment by AIZOOTech** [comment]
If you want to use it on Android, you need to wirte the corresponding decode and nms codes. You can refer to our python decode and nms function to write the Java or C codes.&nbsp;
Are you Chinese? If yes, you can add my wechat: AIZOOTech. We have written an Android demo.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Frank Chu"; 
Date: 2020年4月30日(星期四) 下午3:05
To: "AIZOOTech/FaceMaskDetection"; 
Cc: "Subscribed"; 
Subject: [AIZOOTech/FaceMaskDetection] i open face_mask_detection.tflite via Netron, why the dimension of this are [1, 5972, 4] and [1,5972, 2] ? (#40)

&nbsp;


 
I want to use face_mask_detection.tflite port into android.
 and there is a question, why label just 2 type [NoMask, Mask], but the dimension of this file are [1, 5972, 4] and [1,5972, 2] ?

**Comment by laihaotao** [comment]
is it the android code opensource at somewhere?

**Comment by tomeroto** [comment]
there is example for android?
