### ISSUE TITLE
Precision and Recall

### ISSUE THREAD

**Issue by FrankXinqi** [AIZOOTech/FaceMaskDetection#44]
There is a PR curve provided in the readme. Could you also please provide your best precision and recall? Thx

**Comment by AIZOOTech** [comment]
@FrankXinqi We train the model with 360x360, the mAP get much higher, if you need it, please leave you email.

**Comment by fuyimin96** [comment]
@AIZOOTech  Hi, can you please give me the mAP you got?
thanks,
my address is y_fu@etud.insa-toulouse.fr

**Comment by AIZOOTech** [comment]
@fuyimin96  face 0.896, face with mask 0.919.
