### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by tempdata73** [AIZOOTech/FaceMaskDetection#51]
I was just wondering in what Pytorch version were the models trained on? I want to get rid of those pesky SourceChange warnings...

Thank you for releasing these models!

**Comment by AIZOOTech** [comment]
I trained this model with keras, then I convert the model to PyTorch version. You can load the model, and save it again. Maybe this can solve the warning message.

**Comment by twmht** [comment]
is pytorch really from keras?

I convert mxnet model (I believe this is also from keras) to pytorch, but with input 360x360, the number of the generated bounding boxes are always 2 for one face.
