### ISSUE TITLE
输入大小固定，修改成520*520报错

### ISSUE THREAD

**Issue by gengyanlei** [AIZOOTech/FaceMaskDetection#6]
1. 输入大小被固定
2.泛化性较差
![1](https://user-images.githubusercontent.com/22360785/75147058-68208180-5737-11ea-8d5d-f1333db9bf71.jpg)

**Comment by AIZOOTech** [comment]
1. 谢谢你的意见，后面我把输入改成不固定，模型也可以提供多尺度的训练方式。
2. 模型输入太小，主干网络只有8个卷积层，数据也比较简单，对小人脸检测不佳。
3.本开源的模型只是demo用，如果要用在工业界，需要训练大模型

**Comment by gengyanlei** [comment]
谢谢作者的回复，我只是想看看它在视频中的一个效果。
