### ISSUE TITLE
 How to use it as a webcam, upload it to .ipynb

### ISSUE THREAD

**Issue by Asankorean** [AIZOOTech/FaceMaskDetection#60]
I don't understand

**Comment by AIZOOTech** [comment]
You can use `python tensorflow_infer.py --img-mod=0` to use web cam

**Comment by Asankorean** [comment]
tensorflow_infer.py --img-mod=0 로 해보았지만 웹캠모드가 안된다. 웹캠으로 사용하는 .ipynb파일을 올려줄수 있냐?

**Comment by Asankorean** [comment]
I tried tensorflow_infer.py --img-mod = 0 but webcam mode is not working. Can you upload the .ipynb file used as a webcam?

**Comment by AIZOOTech** [comment]
I am sorry, I cannot understand Korean。
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Asankorean"; 
Date: 2020年5月30日(星期六) 中午12:10
To: "AIZOOTech/FaceMaskDetection"; 
Cc: "AIZOOTech"; "Comment"; 
Subject: Re: [AIZOOTech/FaceMaskDetection]  How to use it as a webcam, upload it to .ipynb (#60)

&nbsp;


 
tensorflow_infer.py --img-mod=0 로 해보았지만 웹캠모드가 안된다. 웹캠으로 사용하는 .ipynb파일을 올려줄수 있냐?
