### ISSUE TITLE
 How to use in Raspberry Pi??

### ISSUE THREAD

**Issue by Asankorean** [AIZOOTech/FaceMaskDetection#65]
tersorflow_infer.py doesn't run on Raspberry Pi.

**Comment by AIZOOTech** [comment]
I do not have experience of runing Raspherry PI. Does it need to use tflite to run?&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Asankorean"; 
Date: 2020年6月2日(星期二) 晚上7:15
To: "AIZOOTech/FaceMaskDetection"; 
Cc: "Subscribed"; 
Subject: [AIZOOTech/FaceMaskDetection]  How to use in Raspberry Pi?? (#65)

&nbsp;


 
tersorflow_infer.py doesn't run on Raspberry Pi.
