### ISSUE TITLE
Complete Model

### ISSUE THREAD

**Issue by tulasiram58827** [AIZOOTech/FaceMaskDetection#68]
Do you have any plan to release the full model

**Comment by AIZOOTech** [comment]
We  lack the images of street view. If you have those dataset, you can send them to me to train a full  model.

**Comment by tulasiram58827** [comment]
I think this is the main problem now. Why dont we colloborate and create dataset from the videos available?

**Comment by AIZOOTech** [comment]
Good idea. How to build a corporate team?



发自我的iPhone


------------------ Original ------------------

**Comment by tulasiram58827** [comment]
I don't know. You can suggest something

**Comment by ZIKO94ZIKO** [comment]
@AIZOOTech  how about this datsets?? [Dataset](https://translate.googleusercontent.com/translate_c?depth=1&hl=fr&nv=1&pto=aue&rurl=translate.google.com&sl=auto&sp=nmt4&tl=en&u=https://github.com/X-zhangyang/Real-World-Masked-Face-Dataset/blob/master/README.md&usg=ALkJrhgBHaUNWvHV09W4rqeyssV0hw0jag)

**Comment by tulasiram58827** [comment]
@ZIKO94ZIKO I checked them already but they did not look like street view images.

**Comment by ZIKO94ZIKO** [comment]
Ok , @tulasiram58827  how can be collecte the datastes , take a lot of photos with drones? or camera cctv?

**Comment by tulasiram58827** [comment]
I think we need to collecte some videos from cctv somehow and label them manually with labelImg tool

**Comment by AIZOOTech** [comment]
@tulasiram58827 Good idea

**Comment by ZIKO94ZIKO** [comment]
@tulasiram58827 lets start to collect datasets  , if any one have a video or link video about musk , put the links here . thanks

**Comment by ZIKO94ZIKO** [comment]
[](https://www.youtube.com/watch?v=41Zc30xrrbM) @tulasiram58827  tell me sir ,should choosing like  this video ?

**Comment by ZIKO94ZIKO** [comment]
[]()https://m.youtube.com/watch?v=41Zc30xrrbM

**Comment by ZIKO94ZIKO** [comment]
[](dataset)https://drive.google.com/folderview?id=12BdrTdAfd8lJPQqexyFU3kbFClHdsDtc @tulasiram58827 can you please take a look at this

**Comment by tulasiram58827** [comment]
@AIZOOTech I found this amazing dataset in Kaggle. https://www.kaggle.com/vtech6/medical-masks-dataset. Check it once it will serve our purpose

**Comment by zongoalbert** [comment]
@tulasiram58827  check also this question : #66

**Comment by ZIKO94ZIKO** [comment]
Hello everyone ,any updates?!
