### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by DarrenmondZhang** [AIZOOTech/FaceMaskDetection#7]
您好，我想用您的数据集在YOLOV3上做训练一下，尝试一下，当我尝试将xml文件转换为YOLOV3所需要的格式的时候，很多xml文件缺少`size`信息（图片大小的信息）。我想问一下，是我下载文件的问题，还是您的数据集本身就没有这个信息

```
<annotation>
	<folder>/home/daniel/Data/Dataset/FaceMaskNew/train_mafa</folder>
	<filename>test_00001347.xml</filename>
	<object>
		<name>face_mask</name>
		<difficult>0</difficult>
		<bndbox>
			<xmin>131</xmin>
			<ymin>71</ymin>
			<xmax>244</xmax>
			<ymax>219</ymax>
		</bndbox>
	</object>
</annotation>
```

这是test_00001347.jpg的xml文件

**Comment by AIZOOTech** [comment]
不好意思，是我忘记加入了，因为我训练的代码，是从图片读取width和height。建议您写个脚本，给xml文件加上size属性。再次抱歉～

**Comment by DarrenmondZhang** [comment]
好的 谢谢您   感谢您能开源数据集

**Comment by DarrenmondZhang** [comment]
哎呀  我咋没想到呢  我也可以从图片读取， 我用了一下午时间一个个往xml文件中添加   我真的是   哈哈哈哈  感谢大佬提醒

**Comment by DuckJ** [comment]
请问百度云提供的数据包含五点么
