### ISSUE TITLE
How to train?

### ISSUE THREAD

**Issue by PrakharPrashantSingh** [AIZOOTech/FaceMaskDetection#81]
i want to retrain it for better accuracy, can you tell me how to retrain it without breaking anything!
Thanks for awesome work

**Comment by BOLIU68520** [comment]
Obviously, this is a model and weight only project cannot be trained, no loss,so,give it up

**Comment by PrakharPrashantSingh** [comment]
okay @BOLIU68520 , thanks for the info!
